version: '2'
services:
    project1-app:
        image: project1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://project1-mysql:3306/project1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    project1-mysql:
        extends:
            file: mysql.yml
            service: project1-mysql
